name: Claude Code Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
    - name: Claude Code Action
      uses: anthropics/claude-code-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        
    - name: Run tests after Claude changes
      if: github.event_name == 'pull_request'
      run: |
        npm ci
        npm start &
        sleep 10
        npx playwright install --with-deps
        npm test