name: Claude GitHub App Integration

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # This workflow is designed for Claude GitHub App users (Claude Max subscription)
  # The Claude GitHub App will automatically respond to @claude mentions
  # This job provides additional testing after Claude interactions
  
  test-after-claude:
    name: Test After Claude Interaction
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start application server
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3001 || exit 1
        
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run tests after Claude interaction
      run: npm test
      env:
        CI: true
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: claude-interaction-test-results
        path: playwright-report/
        retention-days: 7
        
    - name: Comment test results
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue_number = context.issue.number;
          const body = `❌ **Tests Failed After Claude Interaction**
          
          The automated tests failed after Claude's interaction. Please check the test results and address any issues.
          
          [View Test Results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
          
          if (context.eventName === 'issue_comment' || context.eventName === 'issues') {
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });
          }

  claude-app-info:
    name: Claude App Information
    if: contains(github.event.comment.body, '@claude help') || contains(github.event.issue.body, '@claude help')
    runs-on: ubuntu-latest
    
    steps:
    - name: Provide Claude App Information
      uses: actions/github-script@v7
      with:
        script: |
          const issue_number = context.issue.number;
          const body = `🤖 **Claude GitHub App Information**
          
          This repository has the Claude GitHub App installed! Here's how to use it:
          
          ## Available Commands:
          - \`@claude\` - Ask questions about the code
          - \`@claude fix this bug\` - Request bug fixes
          - \`@claude review this PR\` - Request code review
          - \`@claude explain this function\` - Get code explanations
          - \`@claude add tests for this feature\` - Request test additions
          
          ## Features:
          ✅ Code analysis and explanations
          ✅ Bug detection and fixes
          ✅ Test generation
          ✅ Code review assistance
          ✅ Documentation updates
          
          ## Testing:
          After Claude makes changes, automated tests will run to ensure code quality.
          
          *Note: This repository uses Claude Max subscription via GitHub App integration.*`;
          
          if (context.eventName === 'issue_comment' || context.eventName === 'issues') {
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });
          }